--1. List all unique cities where customers are located.
select 
	distinct customer_city 
from customers

--2. Count the number of orders placed in 2017.
select count(*)
from orders
where EXTRACT(YEAR FROM order_purchase_timestamp::DATE) =2017

--3. Find the total sales per category.
select 
	upper(products.product_category) as category,
	round(sum(payments.payment_value)::numeric,2) as sales
	from products
	join order_items
	on products.product_id = order_items.product_id
	join payments
	on payments.order_id = order_items.order_id
group by category


--4. Calculate the percentage of orders that were paid in installments.
select 
	round(
		sum(
		case 
			when payment_installments >=1 then 1
			else 0
		end
	)/count(*)::numeric*100,3
	)
from payments

--5. Count the number of customers from each state. 
select
customer_state,
count(*) as total_customer
from customers
group by 1


--6. Calculate the number of orders per month in 2018.
select 
	to_char(order_purchase_timestamp::date, 'Month') as Months,
	count(*)
from orders
where extract(Year from order_purchase_timestamp::date) = 2018
group by Months

--7. Find the average number of products per order, grouped by customer city.

with count_per_order as 
(select 
	orders.order_id, 
	orders.customer_id, 
	count(order_items.order_id) as oc
from orders join order_items
on orders.order_id = order_items.order_id
group by orders.order_id, orders.customer_id)

select 
	customers.customer_city, 
	round(avg(count_per_order.oc),2) average_orders
from customers join count_per_order
on customers.customer_id = count_per_order.customer_id
group by customers.customer_city 
order by average_orders desc


--8. Calculate the percentage of total revenue contributed by each product category.
select 
	upper(products.product_category) category,
	round((sum(payments.payment_value::numeric)/(
												select sum(payment_value::numeric) 
												from payments))*100,2) sales_percentage
from products 
	join order_items 
	on products.product_id = order_items.product_id
	join payments 
	on payments.order_id = order_items.order_id
group by category 
order by sales_percentage desc

--9. Identify the correlation between product price and the number of times a product has been purchased.
select 
	products.product_category, 
	count(order_items.product_id),
	round(avg(order_items.price::numeric),2)
from products join order_items
on products.product_id = order_items.product_id
group by products.product_category

--10. Calculate the total revenue generated by each seller, and rank them by revenue
select 
	*, 
	dense_rank() over(order by revenue desc) as rn 
from (
		select 
			order_items.seller_id, 
			sum(payments.payment_value) revenue 
		from order_items 
		join payments
		on order_items.order_id = payments.order_id
		group by order_items.seller_id)


--11. Calculate the moving average of order values for each customer over their order history.
select 
	customer_id, 
	order_purchase_timestamp, 
	payment,
	avg(payment) over(partition by customer_id order by order_purchase_timestamp
		rows between 2 preceding and current row) as mov_avg
from
(select 
	orders.customer_id, 
	orders.order_purchase_timestamp, 
	payments.payment_value as payment
from payments join orders
on payments.order_id = orders.order_id)

--12. Calculate the cumulative sales per month for each year.
select 
	years, 
	months , 
	payment, 
	sum(payment) over(order by years, months) cumulative_sales 
from (select 
		extract(year from orders.order_purchase_timestamp::date) as years,
		extract(month from orders.order_purchase_timestamp::date) as months,
		round(sum(payments.payment_value::numeric),2) as payment 
	from orders join payments
	on orders.order_id = payments.order_id
	group by years, 
	months order by years, months) as a

--13. Calculate the year-over-year growth rate of total sales.
with a 
as
(select 
	extract(year from orders.order_purchase_timestamp::date) as years,
	round(sum(payments.payment_value::numeric),2) as payment 
from orders join payments
on orders.order_id = payments.order_id
group by years 
order by years
)

select 
	years, 
	((payment - lag(payment, 1) over(order by years))/lag(payment, 1) over(order by years)) * 100 
from a

/*
14. Calculate the retention rate of customers, defined as the percentage of customers who make another purchase 
within 6 months of their first purchase.
*/
with a 
as 
(
select 
	customers.customer_id,
	min(orders.order_purchase_timestamp::date) first_order
from customers join orders
on customers.customer_id = orders.customer_id
group by customers.customer_id
),

b as 
(
select 
	a.customer_id, 
	count(distinct orders.order_purchase_timestamp::date) next_order
from a join orders
on orders.customer_id = a.customer_id
where	orders.order_purchase_timestamp::date > first_order
	    and orders.order_purchase_timestamp::date < first_order + INTERVAL '6 months'
group by a.customer_id
) 

select 
	100 * (count( distinct a.customer_id)/ count(distinct b.customer_id)) 
from a left join b 
on a.customer_id = b.customer_id ;

--15. Identify the top 3 customers who spent the most money in each year.
select 
years, 
customer_id, 
payment, r_rank
from (
		select 
			extract(year from orders.order_purchase_timestamp::date) years,
			orders.customer_id,
			sum(payments.payment_value::numeric) payment,
			dense_rank() over(partition by extract(year from orders.order_purchase_timestamp::date)
				order by sum(payments.payment_value::numeric) desc) r_rank
		from 
		orders join payments 
		on payments.order_id = orders.order_id
		group by extract(year from orders.order_purchase_timestamp::date),orders.customer_id
	) as a
where r_rank <= 3 

























